import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { HexclaveProvider, HexclaveTheme } from "@hexclave/next";
import { hexclaveServerApp } from "@/hexclave/server";
import { Navbar } from "@/components/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cloves and Cinnamon",
  description: "A blogging site generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <HexclaveProvider app={hexclaveServerApp}>
          <HexclaveTheme>
            <Navbar />
            {children}
          </HexclaveTheme>
        </HexclaveProvider>
      </body>
    </html>
  )
}
